apiVersion: apps/v1 
kind: Deployment
metadata:
  name: security
  labels: 
     app: security

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: security

  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
      - name: security
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 5006
        env:
        - name: AWS_ACCESS_KEY_ID
          value: ENV1
        - name: AWS_SECRET_ACCESS_KEY
          value: ENV2
        - name: APP_SPORTAPP
          value: ENV3
        - name: APP_SPORTAPPCLIENT
          value: ENV4
        - name: APP_SPORTAAIDGRUPO
          value: ENV5  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
