apiVersion: v1
kind: Service
metadata:
  name: security
  labels:
    app: security
spec:
  selector:
    app: security
  ports:
    - port: 80
      targetPort: 5006

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: security-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: a1b7563a0858f4f71b48c713a5de8c20-991979942.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /security
            pathType: Prefix
            backend:
              service:
                name: security
                port:
                  number: 80
