apiVersion: v1
kind: Service
metadata:
  name: security
  labels:
    app: security
spec:
  selector:
    app: security
  ports:
    - port: 80
      targetPort: 5006

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: security-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: a30e8ad80d7ce496f87c317e39919031-393841883.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /security
            pathType: Prefix
            backend:
              service:
                name: security
                port:
                  number: 80
